# Generated by scripts/refresh_ollama_cloud_catalog.py — do not edit by hand.
#
# Membership: https://ollama.com/v1/models (snapshot 2026-08-10)
# Metadata:   https://ollama.com/api/show (snapshot 2026-08-10)
#
# 18 models containing both completion and tools capabilities.
#
# Regenerate with: uv run python scripts/refresh_ollama_cloud_catalog.py

from kolega_code.llm.specs.types import ThinkingEffortSpec

OLLAMA_CLOUD_SPECS = {
    ("ollama_cloud", "deepseek-v4-flash:0731"): {
        "context_length": 1048576,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "deepseek-v4-flash:preview"): {
        "context_length": 1048576,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "deepseek-v4-pro"): {
        "context_length": 524288,
        "max_completion_tokens": 65536,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "gemma4:31b"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "glm-5.1"): {
        "context_length": 202752,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "glm-5.2"): {
        "context_length": 1000000,
        "max_completion_tokens": 65536,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "gpt-oss:120b"): {
        "context_length": 131072,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "gpt-oss:20b"): {
        "context_length": 131072,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "kimi-k2.6"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "kimi-k2.7-code"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "kimi-k3"): {
        "context_length": 1048576,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "minimax-m2.7"): {
        "context_length": 196608,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "minimax-m3"): {
        "context_length": 524288,
        "max_completion_tokens": 65536,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "mistral-large-3:675b"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
    },
    ("ollama_cloud", "nemotron-3-nano:30b"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "nemotron-3-super"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "nemotron-3-ultra"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": False,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
    ("ollama_cloud", "qwen3.5:397b"): {
        "context_length": 262144,
        "max_completion_tokens": 32768,
        "default_temperature": 1.0,
        "supports_vision": True,
        "thinking_effort": ThinkingEffortSpec(
            options=("low", "medium", "high"),
            default="medium",
            mode="openai_reasoning_effort",
        ),
    },
}
