"""Typed base class for TUI mixins.

``KolegaCodeApp`` composes six behavior mixins over Textual's ``App``.  Each
mixin accesses attributes and methods defined in ``KolegaCodeApp.__init__`` or on
sibling mixins.  Without a common typed base, pyright cannot resolve those
references and reports hundreds of ``reportAttributeAccessIssue`` errors.

``KolegaAppBase`` inherits from ``App`` so every mixin that derives from it
picks up Textual's own methods (``query_one``, ``run_worker``, etc.).  All
shared instance attributes and cross-mixin method signatures are declared under
an ``if TYPE_CHECKING:`` block so they exist only for the type checker — no
runtime attributes or methods are introduced, keeping MRO resolution and
Textual behavior identical.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, TypeVar

from textual.app import App

ScreenResultT = TypeVar("ScreenResultT")

if TYPE_CHECKING:
    import asyncio

    from pathlib import Path

    from textual.screen import Screen
    from textual.timer import Timer
    from textual.worker import Worker

    from kolega_code.agent import AgentConfig, AgentEvent, BaseAgent, PromptExtension, ToolExtension
    from kolega_code.hooks import HookDispatcher
    from kolega_code.memory import ProjectMemoryManager
    from kolega_code.permissions import PermissionDecision, PermissionMode, PermissionRequest

    from ..config import CliConfigOverrides
    from ..connection import CliConnectionManager
    from ..diagnostics import DiagnosticsLog, ResponsivenessWatchdog
    from ..file_index import WorkspaceFileIndex
    from ..goal import GoalState
    from ..session_journal import SessionRecorder
    from ..session_store import SessionRecord, SessionStore
    from ..settings import CliSettings, SettingsStore
    from ..skills import SkillCatalog

    from . import state as tui_state
    from . import widgets as tui_widgets
    from .changes_screen import ChangesInspectorScreen
    from .memory_screen import MemoryScreen
    from .onboarding_screen import OnboardingScreen
    from .session_diff import SessionDiffFile, SessionDiffTrackerBase, TurnCheckpoint
    from .settings_screen import SettingsScreen
    from .sub_agent_screen import SubAgentInspectorScreen
    from .terminal_display import TerminalDisplayNormalizer


class KolegaAppBase(App):
    """Typed base for all TUI mixins.

    All declarations below are ``TYPE_CHECKING``-only — they exist solely so
    pyright can resolve cross-mixin attribute and method references.  At runtime
    this class is indistinguishable from ``App`` itself.
    """

    if TYPE_CHECKING:
        # ------------------------------------------------------------------
        # Instance attributes (set in KolegaCodeApp.__init__)
        # ------------------------------------------------------------------
        project_path: Path
        config: AgentConfig | None
        mode: str
        store: SessionStore
        session: SessionRecord
        _session_recorder: SessionRecorder
        interaction_mode: str
        permission_mode: PermissionMode
        settings_store: SettingsStore
        memory_manager: ProjectMemoryManager
        overrides: CliConfigOverrides
        settings: CliSettings
        skill_catalog: SkillCatalog
        file_index: WorkspaceFileIndex
        _file_index_refreshing: bool
        _diag: DiagnosticsLog | None
        _watchdog: ResponsivenessWatchdog | None
        browser_visible: bool
        sidebar_visible: bool
        check_for_updates: bool
        show_logs: bool
        startup_config_error: str | None
        _settings_screen: SettingsScreen | None
        _memory_screen: MemoryScreen | None
        _onboarding_screen: OnboardingScreen | None
        _onboarding_skipped: bool
        connection_manager: CliConnectionManager
        _hook_dispatcher: HookDispatcher | None
        _session_started: bool
        agent: BaseAgent | None
        agent_worker: Worker | None
        conversation_entries: list[tui_state.ConversationEntry]
        _stream_entries: dict[str, tui_state.ConversationEntry]
        _tool_entries: dict[str, tui_state.ConversationEntry]
        _tool_stream_buffers: dict[str, str]
        _sub_agent_activities: dict[str, tui_state.SubAgentActivity]
        _sub_agent_by_tool_call: dict[str, str]
        _sub_agent_seq: int
        _session_file_changes: list[tui_state.SessionFileChange]
        _session_diff_tracker: SessionDiffTrackerBase | None
        _session_diff_files: list[SessionDiffFile]
        _session_diff_dirty: bool
        _session_diff_refresh_running: bool
        _session_diff_timer: Timer | None
        _session_diff_baseline_id: int | None
        _rewind_running: bool
        _workflow_activities: dict[str, tui_state.WorkflowActivity]
        _render_pending: bool
        _conversation_anchor_pending: bool
        _transcript_window: tui_widgets.ScrollbackWindow | None
        _transcript_sync_pending: bool
        _rendered_entry_count: int
        _dirty_entry_ids: set[str]
        _active_progress_entry: tui_state.ConversationEntry | None
        _turn_active: bool
        _latest_plan: str | None
        _plan_pending: bool
        _plan_reofferable: bool
        _plan_decision_active: bool
        _gigacode_enabled: bool
        _goal: GoalState | None
        _pending_question: tui_state.PendingQuestion | None
        _pending_approval: tui_state.PendingApproval | None
        _pending_image_attachments: list[dict]
        _queued_messages: list[tui_state.QueuedMessage]
        _queued_message_seq: int
        _vision_warning_shown: bool
        _permission_lock: asyncio.Lock
        _persistence_lock: asyncio.Lock
        _pending_model_selection: tui_state.PendingModelSelection | None
        _pending_effort_selection: tui_state.PendingEffortSelection | None
        _pending_theme_selection: tui_state.PendingThemeSelection | None
        _pending_agent_models: dict[str, str]
        _pending_agent_efforts: dict[str, str]
        _status_state: tui_state.StatusDashboardState
        _turn_started_at: float | None
        _turn_finished_duration: float | None
        _turn_timer: Timer | None
        _turn_status_text: str
        _turn_final_text: str
        _turn_final_state: tui_state.TurnState
        _last_turn_status_content: str | None
        _spinner_frame: int
        _last_sub_agent_tick: float
        _sub_agent_inspector: SubAgentInspectorScreen | None
        _changes_inspector: ChangesInspectorScreen | None
        _terminal_has_content: bool
        _terminal_output_buffer: list[str]
        _terminal_output_buffer_chars: int
        _terminal_flush_timer: Timer | None
        _terminal_display_normalizer: TerminalDisplayNormalizer
        _log_output_buffer: list[object]
        _log_flush_timer: Timer | None

        # ------------------------------------------------------------------
        # Properties (defined on KolegaCodeApp)
        # ------------------------------------------------------------------
        @property
        def _conversation(self) -> tui_widgets.ConversationView: ...

        @property
        def _logs(self) -> tui_widgets.LogOutputLog: ...

        @property
        def _terminal(self) -> tui_widgets.TerminalOutputLog: ...

        @property
        def _entry_widgets(self) -> dict[str, tui_widgets.ConversationEntryWidget | tui_widgets.ToolEntryWidget]: ...

        @property
        def _modal_cover_active(self) -> bool: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — app.py
        # ------------------------------------------------------------------
        def _add_conversation_entry(self, entry: tui_state.ConversationEntry) -> None: ...
        def _build_mention_attachments(self, text: str) -> list[dict] | None: ...
        def _clear_composer_hint(self) -> None: ...
        def _close_sub_agent_inspector(self) -> None: ...
        def _diagnostics_header(self) -> dict: ...
        def _ensure_startup_entry(self, *, render: bool = True) -> None: ...
        def _flush_log_output(self) -> None: ...
        def _flush_terminal_output(self) -> None: ...
        def _focus_active_prompt(self) -> None: ...
        def _log_status(self, text: str, level: str = "info") -> None: ...
        def _mark_session_diff_dirty(self) -> None: ...
        def _maybe_expand_transcript_window(self) -> None: ...
        def _on_fullscreen_modal_dismissed(self, _result: object = None) -> None: ...
        def _push_fullscreen_modal(self, screen: Screen[ScreenResultT]) -> None: ...
        def _changes_available(self) -> bool: ...
        def _changes_baseline_ladder(self) -> list[int]: ...
        def _changes_baseline_checkpoint(self) -> TurnCheckpoint | None: ...
        def _changes_baseline_label(self) -> str: ...
        def _set_changes_baseline(self, baseline_id: int | None) -> None: ...
        def _shift_changes_baseline(self, delta: int) -> None: ...
        def _reset_changes_baseline(self) -> None: ...
        def _initialize_ledger_diff_tracker(self) -> None: ...
        def action_open_changes(self, path: str | None = None, *, baseline_id: int | None = None) -> None: ...
        async def _rewind_worker(self, baseline_id: int | None, label: str, paths: set[str] | None = None) -> None: ...
        async def _apply_memory_enabled(self, enabled: bool) -> None: ...
        def _memory_mutation_blocked(self) -> bool: ...
        def _mode_switch_blocked(self) -> bool: ...
        def _notify_user(self, message: str, *, severity: str = "information", title: str | None = None) -> None: ...
        def _permission_mode_switch_blocked(self) -> bool: ...
        def _queue_terminal_output(self, output: str) -> None: ...
        def _refresh_input_area_visibility(self) -> None: ...
        def _refresh_planning_sidebar(self) -> None: ...
        def _restore_composer_placeholder(self) -> None: ...
        def _restore_plan_action_visibility(self) -> None: ...
        async def _save_session_async(self) -> None: ...
        async def _refresh_agent_memory(self) -> None: ...
        async def _save_session_history_async(self) -> None: ...
        async def _capture_completed_plan(self) -> None: ...
        def _schedule_primary_focus_restore(self) -> None: ...
        def _set_chat_enabled(self, enabled: bool) -> None: ...
        def _set_composer_status(self, status: str) -> None: ...
        def _set_effort_actions_visible(self, visible: bool) -> None: ...
        async def _set_interaction_mode(self, interaction_mode: str) -> None: ...
        def _set_model_actions_visible(self, visible: bool) -> None: ...
        async def _set_permission_mode(self, permission_mode: PermissionMode | str) -> None: ...
        def _set_theme_actions_visible(self, visible: bool) -> None: ...
        def _show_composer_hint(self, text: str, tone: str = "warning") -> None: ...
        def _start_session_diff_refresh(self) -> None: ...
        def _startup_model(self) -> tuple[str, str]: ...
        def _startup_thinking_effort(self) -> str | None: ...
        def _update_mode_chrome(self) -> None: ...
        def _write_log(self, text: str, level: str = "info") -> None: ...
        def _write_terminal_command(self, command: str) -> None: ...
        async def action_quit(self) -> None: ...
        async def action_toggle_permission_mode(self) -> None: ...
        async def action_toggle_sidebar(self) -> None: ...
        def action_open_onboarding(self) -> None: ...
        def action_open_memory(self, *, inspect_disabled: bool = False) -> None: ...
        def action_open_settings(self, category: str = "model") -> None: ...
        def copy_to_clipboard(self, text: str) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — agent_runtime.py
        # ------------------------------------------------------------------
        async def _clear_active_goal(self, *, note: str | None = None) -> None: ...
        def _clear_queued_messages(self) -> int: ...
        async def _ensure_agent_from_settings(self, rebuild: bool = False) -> None: ...
        def _format_lsp_status(self) -> str: ...
        async def _persist_goal_async(self) -> None: ...
        async def _process_message(
            self, message: str, attachments: list[dict] | None = None, *, turn_label: str | None = None
        ) -> None: ...
        def _set_goal_state(self, goal: GoalState) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — command_handlers.py
        # ------------------------------------------------------------------
        def _apply_theme(self, name: str | None) -> None: ...
        def _gigacode_prompt_extension(self) -> PromptExtension: ...
        async def _paste_clipboard_image_worker(self) -> None: ...
        def add_pending_image_attachment(self, attachment: dict) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — prompt_flows.py
        # ------------------------------------------------------------------
        def _cancel_pending_approval(self) -> None: ...
        def _cancel_pending_effort_selection(self) -> None: ...
        def _cancel_pending_model_selection(self) -> None: ...
        def _cancel_pending_question(self) -> None: ...
        def _cancel_pending_theme_selection(self) -> None: ...
        def _planning_question_prompt_extension(self) -> PromptExtension: ...
        def _planning_question_tool_extension(self) -> ToolExtension: ...
        async def _permission_callback(self, request: PermissionRequest) -> PermissionDecision: ...
        def _shared_task_list_prompt_extension(self) -> PromptExtension: ...
        def _shared_task_list_tool_extension(self) -> ToolExtension: ...
        def _show_effort_options(self) -> None: ...
        def _show_model_options(self) -> None: ...
        def _show_theme_options(self) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — status_dashboard.py
        # ------------------------------------------------------------------
        def _apply_compaction_status(self, content: dict) -> None: ...
        def _apply_context_status_update(self, content: dict) -> None: ...
        def _as_optional_float(self, value: object) -> float | None: ...
        def _as_optional_int(self, value: object) -> int | None: ...
        def _complete_turn_timer(self, content: str, state: tui_state.TurnState = tui_state.TurnState.IDLE) -> None: ...
        def _display_text_from_event(self, event: AgentEvent) -> str: ...
        def _format_turn_duration(self, seconds: float) -> str: ...
        def _now(self) -> float: ...
        def _refresh_status_dashboard(self) -> None: ...
        def _refresh_turn_status_strip(self) -> None: ...
        def _set_status_activity(self, content: str, *, turn_state: tui_state.TurnState | None = None) -> None: ...
        def _start_turn_timer(self, status_text: str) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — transcript.py
        # ------------------------------------------------------------------
        def _add_tool_message(self, message_type: str, content: dict) -> None: ...
        def _apply_edit_preview(self, content: dict) -> None: ...
        def _apply_stream_chunk(self, chunk: dict, *, kind: str) -> None: ...
        def _apply_sub_agent_edit_preview(self, event: AgentEvent) -> None: ...
        def _apply_tool_streaming_update(self, content: dict) -> None: ...
        def _begin_turn_progress(self) -> None: ...
        def _finalize_sub_agent_activities(self, status: str = "stopped") -> None: ...
        def _finalize_workflow_activities(self, status: str = "stopped") -> None: ...
        def _finish_turn_progress(
            self, content: str, state: tui_state.TurnState = tui_state.TurnState.IDLE
        ) -> None: ...
        def _flush_conversation_render(self) -> None: ...
        def _get_transcript_window(self) -> tui_widgets.ScrollbackWindow: ...
        def _handle_workflow_end(self, content: dict) -> None: ...
        def _handle_workflow_log(self, content: dict) -> None: ...
        def _handle_workflow_phase(self, content: dict) -> None: ...
        def _handle_workflow_start(self, content: dict) -> None: ...
        def _invalidate_conversation(self, entry: tui_state.ConversationEntry | None) -> None: ...
        def _note_sub_agent_context(self, event: AgentEvent) -> None: ...
        def _note_sub_agent_status(self, event: AgentEvent) -> None: ...
        def _note_sub_agent_tool_stream(self, event: AgentEvent) -> None: ...
        def _record_file_change_event(self, event: AgentEvent) -> tui_state.SessionFileChange | None: ...
        def _render_conversation(self) -> None: ...
        def _render_sub_agent_event(self, event: AgentEvent) -> None: ...
        def _restore_conversation_history(self, history: list[dict]) -> None: ...
        def _tick_running_sub_agents(self) -> None: ...
        def _tick_running_workflows(self) -> None: ...
        def _update_activity_progress(self, content: str, state: tui_state.TurnState | None = None) -> None: ...
        def _update_progress(self, content: str, complete: bool, state: tui_state.TurnState | None = None) -> None: ...

        # ------------------------------------------------------------------
        # Cross-mixin methods — settings_panel.py
        # ------------------------------------------------------------------
        def _populate_settings_controls(self) -> None: ...
        async def _apply_settings_candidate(
            self, candidate: CliSettings, *, rebuild: bool = True
        ) -> tuple[bool, str]: ...
        async def _handle_mcp_settings_button(self, button_id: str) -> bool: ...
        def _refresh_settings_summary(self) -> None: ...
        def _settings_remove_api_key(self) -> None: ...
        def _set_settings_status(self, text: str, tone: str = "info") -> None: ...
        def _update_settings_status(self) -> None: ...
        def _update_lsp_settings_status(self) -> None: ...
