#!/usr/bin/env python3
"""Regenerate ``kolega_code/llm/specs/catalog/ollama_cloud.py`` from Ollama.

Dev-time release chore, never imported by the CLI. Run it from the repo root:

    uv run python scripts/refresh_ollama_cloud_catalog.py

The exact membership list comes from Ollama Cloud's ``/v1/models`` endpoint.
Each returned ID is then resolved through ``/api/show`` for capabilities and
context metadata. Any incomplete response aborts before the existing generated
catalog is replaced.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import runpy
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "kolega_code" / "llm" / "specs" / "catalog" / "ollama_cloud.py"
GENERATOR_REL_PATH = "scripts/refresh_ollama_cloud_catalog.py"

# Importing ``kolega_code.llm.specs`` imports the generated catalog package.
# Seed a placeholder only when the canonical file has been deleted so the
# generator can still import its shared transform and rebuild from scratch.
if not OUTPUT_PATH.exists():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        f"# Placeholder written by {GENERATOR_REL_PATH}; rerun it to populate.\nOLLAMA_CLOUD_SPECS: dict = {{}}\n",
        encoding="utf-8",
    )

from kolega_code.config import ModelProvider  # noqa: E402
from kolega_code.llm.specs import ollama_cloud_catalog as catalog  # noqa: E402


def _default_model() -> str:
    from kolega_code.cli.provider_registry import PROVIDER_DEFAULT_MODEL

    return PROVIDER_DEFAULT_MODEL[ModelProvider.OLLAMA_CLOUD]


def _load_payload(snapshot_file: Optional[str]) -> Any:
    if snapshot_file:
        return json.loads(Path(snapshot_file).read_text(encoding="utf-8"))
    return catalog.fetch_models()


def _load_existing_entries(path: Path) -> list[tuple[str, dict[str, Any]]]:
    if not path.exists():
        return []
    namespace = runpy.run_path(str(path))
    specs = namespace.get("OLLAMA_CLOUD_SPECS")
    if not isinstance(specs, Mapping):
        raise catalog.OllamaCloudCatalogError(f"{path} does not define OLLAMA_CLOUD_SPECS.")

    entries: list[tuple[str, dict[str, Any]]] = []
    for key, spec in specs.items():
        if (
            not isinstance(key, tuple)
            or len(key) != 2
            or key[0] != catalog.PROVIDER
            or not isinstance(key[1], str)
            or not isinstance(spec, Mapping)
        ):
            raise catalog.OllamaCloudCatalogError(f"{path} contains an invalid Ollama Cloud catalog entry.")
        entries.append((key[1], dict(spec)))
    return entries


def _diff_entries(
    previous: Sequence[tuple[str, Mapping[str, Any]]],
    current: Sequence[tuple[str, Mapping[str, Any]]],
) -> tuple[list[str], list[str], list[str]]:
    previous_by_id = {identifier: dict(spec) for identifier, spec in previous}
    current_by_id = {identifier: dict(spec) for identifier, spec in current}
    added = sorted(current_by_id.keys() - previous_by_id.keys())
    removed = sorted(previous_by_id.keys() - current_by_id.keys())
    changed = sorted(
        identifier
        for identifier in previous_by_id.keys() & current_by_id.keys()
        if previous_by_id[identifier] != current_by_id[identifier]
    )
    return added, removed, changed


def _print_ids(label: str, identifiers: Sequence[str]) -> None:
    print(f"{label}: {', '.join(identifiers) if identifiers else '(none)'}")


def _print_report(
    *,
    entries: Sequence[tuple[str, Mapping[str, Any]]],
    added: Sequence[str],
    removed: Sequence[str],
    changed: Sequence[str],
    filtered: Sequence[str],
) -> None:
    print(f"\nEligible models: {len(entries)}")
    _print_ids("Added", added)
    _print_ids("Removed/retired", removed)
    _print_ids("Spec changed", changed)
    _print_ids("Filtered (missing completion/tools)", filtered)


def _header_lines(*, entry_count: int, snapshot_date: str) -> list[str]:
    return [
        f"Generated by {GENERATOR_REL_PATH} — do not edit by hand.",
        "",
        f"Membership: {catalog.MODELS_URL} (snapshot {snapshot_date})",
        f"Metadata:   {catalog.SHOW_URL} (snapshot {snapshot_date})",
        "",
        f"{entry_count} models containing both completion and tools capabilities.",
        "",
        f"Regenerate with: uv run python {GENERATOR_REL_PATH}",
    ]


def _write_generated(output: Path, source: str, *, skip_format: bool) -> bool:
    output.parent.mkdir(parents=True, exist_ok=True)
    compile(source, str(output), "exec")

    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.stem}.",
        suffix=".py",
        dir=output.parent,
        text=True,
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as temporary_file:
            temporary_file.write(source)

        if not skip_format:
            result = subprocess.run(
                ["uv", "run", "ruff", "format", str(temporary_path)],
                cwd=REPO_ROOT,
                check=False,
            )
            if result.returncode != 0:
                print("ERROR: ruff format failed; the existing catalog was not changed.", file=sys.stderr)
                return False

        formatted_source = temporary_path.read_text(encoding="utf-8")
        compile(formatted_source, str(output), "exec")
        temporary_path.chmod(0o644)
        os.replace(temporary_path, output)
        return True
    finally:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--snapshot-file",
        help="Read a combined {'models': ..., 'details': {...}} payload from local JSON instead of the network.",
    )
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Destination generated module path.")
    parser.add_argument("--skip-format", action="store_true", help="Do not run ruff format on generated source.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report semantic drift from the existing output and exit nonzero without writing.",
    )
    args = parser.parse_args(argv)

    print(
        f"Reading {args.snapshot_file}"
        if args.snapshot_file
        else f"Fetching {catalog.MODELS_URL} and model details ..."
    )
    try:
        payload = _load_payload(args.snapshot_file)
        result = catalog.transform_catalog(payload)
        output = Path(args.output)
        previous = _load_existing_entries(output)
    except (OSError, json.JSONDecodeError, catalog.OllamaCloudCatalogError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001 - surface unexpected generated-file failures clearly
        print(f"ERROR: could not refresh the Ollama Cloud catalog: {exc}", file=sys.stderr)
        return 1

    default_model = _default_model()
    current_ids = {entry[0] for entry in result.entries}
    if default_model not in current_ids:
        print(
            f"ERROR: provider default {default_model!r} is absent or not tool-capable. "
            "Choose and review a new Ollama Cloud default before regenerating.",
            file=sys.stderr,
        )
        return 1

    added, removed, changed = _diff_entries(previous, result.entries)
    _print_report(
        entries=result.entries,
        added=added,
        removed=removed,
        changed=changed,
        filtered=result.filtered_ids,
    )

    drifted = bool(added or removed or changed)
    if args.check:
        if drifted:
            print("\nOllama Cloud catalog drift detected.")
            return 1
        print("\nOllama Cloud catalog is up to date.")
        return 0

    source = catalog.render_catalog_module(
        result.entries,
        header_lines=_header_lines(
            entry_count=len(result.entries),
            snapshot_date=dt.date.today().isoformat(),
        ),
    )
    try:
        wrote = _write_generated(output, source, skip_format=bool(args.skip_format))
    except (OSError, SyntaxError) as exc:
        print(f"ERROR: could not write {output}: {exc}", file=sys.stderr)
        return 1
    if not wrote:
        return 1

    print(f"\nWrote {output} ({len(result.entries)} models).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
