#!/usr/bin/env python3
"""Regenerate ``kolega_code/llm/specs/catalog/tinker.py`` from Tinker.

Dev-time release chore, never imported by the CLI. Run it from the repo root:

    uv run python scripts/refresh_tinker_catalog.py

It reads Tinker's published machine-readable model catalog (models.json), the
documented stable interface for scripts. A fetch or transform failure aborts:
guessing model specs is worse than not shipping a refresh.

The transform itself lives in ``kolega_code.llm.specs.tinker_catalog`` so the
runtime ``kolega-code models refresh`` overlay cannot drift from it.
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from pathlib import Path
from typing import Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from kolega_code.llm.specs import tinker_catalog as tinker  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "kolega_code" / "llm" / "specs" / "catalog" / "tinker.py"
GENERATOR_REL_PATH = "scripts/refresh_tinker_catalog.py"

_SNAPSHOT_TEMPLATE = """\
# Generated by {generator} \u2014 do not edit by hand.
#
# Source:  {source} (snapshot {date})
#
# {count} base models. "Base" type models (raw pretrained, no chat template)
# are excluded. Specs are transformed in kolega_code/llm/specs/tinker_catalog.py.
#
# Regenerate with: uv run python {generator}

from kolega_code.llm.specs.types import ThinkingEffortSpec

TINKER_SPECS = {{
{specs}
}}

# Fallback spec for user checkpoints addressed by sampler weights path; the
# provider resolves the checkpoint's real base model at runtime.
TINKER_WILDCARD_SPECS = {{
    ("tinker", "tinker://*"): {{
        "context_length": 65536,
        "max_completion_tokens": 32768,
        "input_budget": "window_minus_output",
        "default_temperature": 1.0,
        "supports_vision": False,
        "preferred_edit_protocol": "claude_code",
    }},
}}
"""


def _format_spec(identifier: str, spec: dict) -> str:
    lines = [f'    ("tinker", "{identifier}"): {{']
    for key, value in spec.items():
        if key == "thinking_effort":
            effort = value
            options = ", ".join(repr(option) for option in effort.options)
            lines.append(
                '        "thinking_effort": ThinkingEffortSpec(\n'
                f"            options=({options}),\n"
                f"            default={effort.default!r},\n"
                f"            mode={effort.mode!r},\n"
                "        ),"
            )
        else:
            lines.append(f"        {key!r}: {value!r},")
    lines.append("    },")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--skip-format", action="store_true", help="Do not run ruff format on the output.")
    args = parser.parse_args(argv)

    date = dt.date.today().isoformat()
    print(f"Fetching {tinker.MODELS_URL} ...")
    payload = tinker.fetch_models()
    entries = tinker.catalog_entries(payload)

    spec_lines = "\n".join(_format_spec(identifier, spec) for identifier, spec in entries)
    OUTPUT_PATH.write_text(
        _SNAPSHOT_TEMPLATE.format(
            generator=GENERATOR_REL_PATH,
            source=tinker.MODELS_URL,
            date=date,
            count=len(entries),
            specs=spec_lines,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(entries)} models to {OUTPUT_PATH}.")
    if not args.skip_format:
        result = subprocess.run(["uv", "run", "ruff", "format", str(OUTPUT_PATH)], cwd=REPO_ROOT)
        if result.returncode != 0:
            print("WARNING: ruff format failed; format the generated file manually.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
