#!/usr/bin/env python3
"""Regenerate ``kolega_code/llm/specs/catalog/openrouter.py`` from OpenRouter.

Dev-time release chore, never imported by the CLI. Run it from the repo root:

    uv run python scripts/refresh_openrouter_catalog.py

It reads two upstream endpoints:

* ``/api/v1/models`` — documented, keyless, and authoritative for every spec
  field. A failure here aborts: guessing model specs is worse than not shipping
  a refresh.
* ``/api/frontend/v1/rankings/models?view=week`` — undocumented; it backs
  OpenRouter's public LLM Leaderboard and decides catalog order and which models
  are ``featured``. A failure here only downgrades ordering to alphabetical and
  preserves whatever featured set the current file already declares, so a
  removed or renamed endpoint can never block a release.

The transform itself lives in ``kolega_code.llm.specs.openrouter_catalog`` so
the runtime ``kolega-code models refresh`` overlay cannot drift from it.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "kolega_code" / "llm" / "specs" / "catalog" / "openrouter.py"
GENERATOR_REL_PATH = "scripts/refresh_openrouter_catalog.py"
REPORT_ROWS = 30

# The generated module is a hard dependency of ``kolega_code.llm.specs.catalog``,
# and importing anything from ``kolega_code`` pulls that in. Seed an empty module
# first so a deleted (or never-generated) catalog can still be regenerated.
if not OUTPUT_PATH.exists():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        f"# Placeholder written by {GENERATOR_REL_PATH}; rerun it to populate.\nOPENROUTER_SPECS: dict = {{}}\n",
        encoding="utf-8",
    )

from kolega_code.config import ModelProvider  # noqa: E402
from kolega_code.llm.specs import openrouter_catalog as catalog  # noqa: E402


def _default_model() -> str:
    """The provider default, which must stay present in the Settings picker."""
    from kolega_code.cli.provider_registry import PROVIDER_DEFAULT_MODEL

    return PROVIDER_DEFAULT_MODEL[ModelProvider.OPENROUTER]


def _existing_featured() -> list[str]:
    """Featured ids declared by the file being replaced, if it exists."""
    try:
        from kolega_code.llm.specs.catalog.openrouter import OPENROUTER_SPECS
    except ImportError:
        return []
    return [key[1] for key, spec in OPENROUTER_SPECS.items() if spec.get("featured")]


def _load_payload(source: Optional[str], fetch, **fetch_kwargs) -> Any:
    """Read a payload from a local file when given, else from the network."""
    if source:
        return json.loads(Path(source).read_text(encoding="utf-8"))
    return fetch(**fetch_kwargs)


def _header_lines(
    *,
    entry_count: int,
    featured_count: int,
    snapshot_date: str,
    rankings_view: Optional[str],
) -> list[str]:
    lines = [
        f"Generated by {GENERATOR_REL_PATH} — do not edit by hand.",
        "",
        f"Models:  {catalog.MODELS_URL} (snapshot {snapshot_date})",
    ]
    if rankings_view:
        lines.append(f"Ranking: {catalog.RANKINGS_URL}?view={rankings_view} (snapshot {snapshot_date});")
        lines.append("         catalog order is OpenRouter leaderboard rank, most-used first.")
    else:
        lines.append("Ranking: unavailable at generation time — catalog order is alphabetical.")
    lines.extend(
        [
            "",
            f"{entry_count} tool-capable models, {featured_count} featured.",
            "Featured models are the ones every picker and the sub-agent model catalog",
            "show; the rest stay selectable by id (--model, /model, settings.json).",
            "",
            f"Regenerate with: uv run python {GENERATOR_REL_PATH}",
        ]
    )
    return lines


def _print_report(
    entries: Sequence[tuple[str, Mapping[str, Any]]],
    scores: Optional[Mapping[tuple[str, str], int]],
    featured: Sequence[str],
    previous_featured: Sequence[str],
    default_model: str,
    ranked_lookup: Mapping[str, int],
) -> None:
    featured_set = set(featured)
    print(f"\nTop {REPORT_ROWS} by weekly token volume:" if scores else f"\nFirst {REPORT_ROWS} entries:")
    for position, (identifier, _) in enumerate(entries[:REPORT_ROWS], start=1):
        marker = "*" if identifier in featured_set else " "
        score = ranked_lookup.get(identifier, 0)
        volume = f"{score / 1e12:.2f}T" if score >= 1e12 else f"{score / 1e9:.0f}B"
        print(f"  {marker} {position:>3}. {identifier:<48} {volume if scores else ''}")

    previous_set = set(previous_featured)
    if previous_set:
        added = [identifier for identifier in featured if identifier not in previous_set]
        removed = [identifier for identifier in previous_featured if identifier not in featured_set]
        print(f"\nFeatured added:   {', '.join(added) if added else '(none)'}")
        print(f"Featured removed: {', '.join(removed) if removed else '(none)'}")

    if scores:
        position = next(
            (index for index, (identifier, _) in enumerate(entries, start=1) if identifier == default_model),
            None,
        )
        if position is None:
            print(f"\nWARNING: provider default {default_model!r} is not in the catalog at all.")
        elif position > catalog.FEATURED_COUNT:
            print(
                f"\nWARNING: provider default {default_model!r} ranks #{position}, outside the top "
                f"{catalog.FEATURED_COUNT}. It is force-featured so the Settings picker still "
                "contains it; consider moving PROVIDER_DEFAULT_MODEL to a more-used model."
            )


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--models-file", help="Read the /api/v1/models payload from a local JSON file.")
    parser.add_argument("--rankings-file", help="Read the rankings payload from a local JSON file.")
    parser.add_argument(
        "--view",
        default=catalog.DEFAULT_RANKINGS_VIEW,
        help=f"Rankings window (default: {catalog.DEFAULT_RANKINGS_VIEW}).",
    )
    parser.add_argument("--no-rankings", action="store_true", help="Skip ranking; emit alphabetical order.")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Destination module path.")
    parser.add_argument("--skip-format", action="store_true", help="Do not run ruff format on the output.")
    args = parser.parse_args(argv)

    print(f"Reading {args.models_file}" if args.models_file else f"Fetching {catalog.MODELS_URL} ...")
    try:
        models_payload = _load_payload(args.models_file, catalog.fetch_models)
    except Exception as exc:  # noqa: BLE001 - the message matters more than the type
        print(f"ERROR: could not read the OpenRouter model list: {exc}", file=sys.stderr)
        return 1

    scores: Optional[dict[tuple[str, str], int]] = None
    rankings_view: Optional[str] = None
    if args.no_rankings:
        print("Ranking skipped (--no-rankings): emitting alphabetical order.")
    else:
        print(
            f"Reading {args.rankings_file}"
            if args.rankings_file
            else f"Fetching {catalog.RANKINGS_URL}?view={args.view} ..."
        )
        try:
            rankings_payload = _load_payload(args.rankings_file, catalog.fetch_rankings, view=args.view)
            scores = catalog.ranking_scores(rankings_payload)
            rankings_view = args.view
        except Exception as exc:  # noqa: BLE001 - undocumented endpoint, must never be fatal
            print(
                "WARNING: the OpenRouter rankings endpoint is undocumented and did not respond "
                f"usefully ({exc}). Falling back to alphabetical order and keeping the existing "
                "featured set.",
                file=sys.stderr,
            )

    previous_featured = _existing_featured()
    default_model = _default_model()

    try:
        entries = catalog.catalog_entries(models_payload, scores)
    except catalog.OpenRouterCatalogError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    catalogued = {identifier for identifier, _ in entries}
    preserved = [identifier for identifier in previous_featured if identifier in catalogued]
    if scores or not preserved:
        # Ranked refresh, or a first generation with nothing to preserve.
        featured = catalog.featured_ids(entries, always_include=[default_model])
    else:
        # Unranked refresh: a transient outage of an undocumented endpoint must
        # not silently rewrite which models the picker offers.
        featured = preserved
        if default_model in catalogued and default_model not in featured:
            featured.append(default_model)

    featured_set = set(featured)
    rendered_entries = [
        (identifier, {**spec, "featured": True} if identifier in featured_set else spec) for identifier, spec in entries
    ]

    source = catalog.render_catalog_module(
        rendered_entries,
        header_lines=_header_lines(
            entry_count=len(rendered_entries),
            featured_count=len(featured_set),
            snapshot_date=dt.date.today().isoformat(),
            rankings_view=rankings_view,
        ),
    )

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")
    print(f"\nWrote {output} ({len(rendered_entries)} models, {len(featured_set)} featured).")

    if not args.skip_format:
        result = subprocess.run(["uv", "run", "ruff", "format", str(output)], cwd=REPO_ROOT)
        if result.returncode != 0:
            print("WARNING: ruff format failed; format the generated file manually.", file=sys.stderr)

    ranked_lookup: dict[str, int] = {}
    if scores:
        rows = models_payload.get("data") if isinstance(models_payload, Mapping) else models_payload
        for entry in rows or []:
            if isinstance(entry, Mapping):
                ranked_lookup[catalog.model_id(entry)] = scores.get(catalog.ranking_key(entry), 0)

    _print_report(rendered_entries, scores, featured, previous_featured, default_model, ranked_lookup)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
